### ISSUE TITLE
update imports of obs_lsstCam=>obs_lsst

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/desc_sim_utils#6]
Hi @jchiang87,  I don't have write access to this repo.  There is a small change to make to support the renamed obs_lsstCam => obs_lsst package:

--- a/python/desc/sim_utils/phosim_repackager.py
+++ b/python/desc/sim_utils/phosim_repackager.py
@@ -11,7 +11,7 @@ from collections import defaultdict
 from astropy.io import fits
 from astropy.utils.exceptions import AstropyWarning, AstropyUserWarning
 import astropy.time
-import lsst.obs.lsstCam as lsstCam
+import lsst.obs.lsst as lsstCam

 __all__ = ['PhoSimRepackager', 'noao_section_keyword']

diff --git a/python/desc/sim_utils/trim_sensors.py b/python/desc/sim_utils/trim_sensors.py
index 735dc2a..75e3d7e 100644
--- a/python/desc/sim_utils/trim_sensors.py
+++ b/python/desc/sim_utils/trim_sensors.py
@@ -5,7 +5,7 @@ given visit.
 import warnings
 import numpy as np
 from lsst.afw import cameraGeom
-import lsst.obs.lsstCam as obs_lsstCam
+import lsst.obs.lsst as obs_lsstCam

**Comment by jchiang87** [comment]
I've added the DC2 team with write access to this repo.
